In [1]:
import pandas as pd
df = pd.read_csv("../data/raw/plastic_waste_state_2016_2021.csv")
df.head()

   Sl. No.      State/UT-wise  2016-17  2017-18    2018-19  2019-20   2020-21
0        1     Andhra Pradesh  82863.0      NaN  66314.000  46222.0  39626.45
1        2  Arunachal Pradesh      NaN      6.0   3787.370   2721.0   3755.90
2        3              Assam  24030.0      NaN  32277.870  24971.0  58765.00
3        4              Bihar   2280.0   2280.0  68903.328  41365.0  74263.69
4        5       Chhattisgarh   7300.0      NaN   6000.000  32850.0  47450.00

In [2]:
df.shape

(35, 7)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Sl. No.        35 non-null     int64
 1   State/UT-wise  35 non-null     str
 2   2016-17        21 non-null     float64
 3   2017-18        13 non-null     float64
 4   2018-19        35 non-null     float64
 5   2019-20        35 non-null     float64
 6   2020-21        34 non-null     float64
dtypes: float64(5), int64(1), str(1)
memory usage: 2.0 KB

In [4]:
df.isna().sum()

Sl. No.           0
State/UT-wise     0
2016-17          14
2017-18          22
2018-19           0
2019-20           0
2020-21           1
dtype: int64

In [5]:
df.tail()

,Sl. No.,State/UT-wise,2016-17,2017-18,2018-19,2019-20,2020-21
30,31,Dadra and Nagar Haveli and Daman and Diu,NaN,NaN,1947.7,1948.0,4726.00
31,32,Chandigarh,21516.75,12775.0,11715.4,6746.0,13107.15
32,33,Lakshadweep,NaN,NaN,148.0,46.0,523.54
33,34,Delhi NCR,232732.00,NaN,224810.0,230525.0,345000.00
34,35,Puducherry,9252.25,NaN,8433.0,11753.0,12754.00

In [6]:
years = ["2016-17", "2017-18", "2018-19", "2019-20", "2020-21"]
df.sort_values("2020-21", ascending=False)[["State/UT-wise", "2020-21"]].head(5)

    State/UT-wise   2020-21
24      Telangana  472675.0
23     Tamil Nadu  430107.0
28    West Bengal  417925.0
26  Uttar Pradesh  375950.0
11      Karnataka  368080.0

In [8]:
df.set_index("State/UT-wise")[years].isna().sum(axis=1).sort_values(ascending=False)

State/UT-wise
Mizoram                                     2
Lakshadweep                                 2
Dadra and Nagar Haveli and Daman and Diu    2
Goa                                         2
West Bengal                                 2
Uttarakhand                                 2
Telangana                                   2
Jharkhand                                   2
Kerala                                      2
Rajasthan                                   2
Arunachal Pradesh                           1
Delhi NCR                                   1
Andaman and Nicobar Islands                 1
Tamil Nadu                                  1
Sikkim                                      1
Nagaland                                    1
Andhra Pradesh                              1
Meghalaya                                   1
Jammu and Kashmir                           1
Assam                                       1
Chhattisgarh                                1
Haryana                                     1
Himachal Pradesh                            1
Manipur                                     1
Puducherry                                  1
Karnataka                                   1
Maharashtra                                 1
Tripura                                     0
Madhya Pradesh                              0
Gujarat                                     0
Punjab                                      0
Chandigarh                                  0
Bihar                                       0
Odisha                                      0
Uttar Pradesh                               0
dtype: int64

In [9]:
df["State/UT-wise"].tolist()

['Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chhattisgarh',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu and Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Odisha',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Telangana',
 'Tripura',
 'Uttar Pradesh',
 'Uttarakhand',
 'West Bengal',
 'Andaman and Nicobar Islands',
 'Dadra and Nagar Haveli and Daman and Diu',
 'Chandigarh',
 'Lakshadweep',
 'Delhi NCR',
 'Puducherry']